[build]
python_version = "3.10"
cuda_version = "12.1"
system_packages = [
    "ffmpeg",
    "libgl1-mesa-glx",
    "libglib2.0-0"
]

[build.python_packages]
torch = "2.1.0"
diffusers = "0.24.0"
transformers = "4.36.0"
runpod = "1.6.0"

[serverless]
handler = "handler.handler"
runtime = "python3.10"
return_aggregate_stream = true

[serverless.env]
CUDA_VISIBLE_DEVICES = "0"
PYTORCH_CUDA_ALLOC_CONF = "max_split_size_mb:512"